pipeline {
    agent any
    environment{
        AWS_ACCESS_KEY_ID = credentials ('AWS_ACCESS_KEY')
        AWS_SECRET_ACCESS_KEY = credentials ('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION = 'ap-south-1'
    }

    stages {
        stage('clone code source') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/nbms12/eks-terraform.git']])
            }
        }
        stage('terraform init') {
            steps {
                script{
                    dir('terraform'){
                        sh 'terraform init'
                    }
                }
            }
        }
        stage('terraform validate') {
            steps {
                script{
                    dir('terraform'){
                        sh 'terraform validate'
                    }
                }
            }
        }
        stage('terraform infra structure checks') {
            steps {
                script{
                    dir('terraform'){
                        sh 'terraform plan'
                    }
                }
            }
        }
         stage('create/destroy eks cluster') {
            steps {
                script{
                    dir('terraform'){
                        sh 'terraform $action --auto-approve'
                    }
                }
            }
        }
    }
}
